include $(THEOS)/makefiles/common.mk

APPEX_NAME = SystemInfoWidget
SystemInfoWidget_FILES = SystemInfoWidgetViewController.mm
SystemInfoWidget_INSTALL_PATH = /Applications/SystemInfo.app/PlugIns
SystemInfoWidget_FRAMEWORKS = UIKit CoreGraphics NotificationCenter
# SystemInfoWidget_CODESIGN_FLAGS = -Sentitlements.plist

include $(THEOS_MAKE_PATH)/appex.mk
